version: '3.8'

services:
  api:
    build: .
    ports:
      - "9001:9000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/api
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 